export interface Country {
  id: string;     // slug identifier
  name: string;   // display and API name
  iso3: string;   // kept for compatibility; set to slug upper where ISO unknown
  flag?: string;
  region?: string;
}

// Alphabetically ordered by name
export const COUNTRIES: Country[] = [
  { id: 'afghanistan', name: 'Afghanistan', iso3: 'AFGHANISTAN' },
  { id: 'albania', name: 'Albania', iso3: 'ALBANIA' },
  { id: 'algeria', name: 'Algeria', iso3: 'ALGERIA' },
  { id: 'angola', name: 'Angola', iso3: 'ANGOLA' },
  { id: 'argentina', name: 'Argentina', iso3: 'ARGENTINA' },
  { id: 'armenia', name: 'Armenia', iso3: 'ARMENIA' },
  { id: 'australia', name: 'Australia', iso3: 'AUSTRALIA' },
  { id: 'austria', name: 'Austria', iso3: 'AUSTRIA' },
  { id: 'azerbaijan', name: 'Azerbaijan', iso3: 'AZERBAIJAN' },
  { id: 'baden', name: 'Baden', iso3: 'BADEN' },
  { id: 'bahrain', name: 'Bahrain', iso3: 'BAHRAIN' },
  { id: 'bangladesh', name: 'Bangladesh', iso3: 'BANGLADESH' },
  { id: 'barbados', name: 'Barbados', iso3: 'BARBADOS' },
  { id: 'bavaria', name: 'Bavaria', iso3: 'BAVARIA' },
  { id: 'belarus', name: 'Belarus', iso3: 'BELARUS' },
  { id: 'belgium', name: 'Belgium', iso3: 'BELGIUM' },
  { id: 'benin', name: 'Benin', iso3: 'BENIN' },
  { id: 'bhutan', name: 'Bhutan', iso3: 'BHUTAN' },
  { id: 'bolivia', name: 'Bolivia', iso3: 'BOLIVIA' },
  { id: 'bosnia-and-herzegovina', name: 'Bosnia and Herzegovina', iso3: 'BOSNIA-AND-HERZEGOVINA' },
  { id: 'botswana', name: 'Botswana', iso3: 'BOTSWANA' },
  { id: 'brazil', name: 'Brazil', iso3: 'BRAZIL' },
  { id: 'brunswick', name: 'Brunswick', iso3: 'BRUNSWICK' },
  { id: 'bulgaria', name: 'Bulgaria', iso3: 'BULGARIA' },
  { id: 'burkina-faso', name: 'Burkina Faso', iso3: 'BURKINA-FASO' },
  { id: 'burma-myanmar', name: 'Burma/Myanmar', iso3: 'BURMA-MYANMAR' },
  { id: 'burundi', name: 'Burundi', iso3: 'BURUNDI' },
  { id: 'cambodia', name: 'Cambodia', iso3: 'CAMBODIA' },
  { id: 'cameroon', name: 'Cameroon', iso3: 'CAMEROON' },
  { id: 'canada', name: 'Canada', iso3: 'CANADA' },
  { id: 'cape-verde', name: 'Cape Verde', iso3: 'CAPE-VERDE' },
  { id: 'central-african-republic', name: 'Central African Republic', iso3: 'CENTRAL-AFRICAN-REPUBLIC' },
  { id: 'chad', name: 'Chad', iso3: 'CHAD' },
  { id: 'chile', name: 'Chile', iso3: 'CHILE' },
  { id: 'china', name: 'China', iso3: 'CHINA' },
  { id: 'colombia', name: 'Colombia', iso3: 'COLOMBIA' },
  { id: 'comoros', name: 'Comoros', iso3: 'COMOROS' },
  { id: 'costa-rica', name: 'Costa Rica', iso3: 'COSTA-RICA' },
  { id: 'croatia', name: 'Croatia', iso3: 'CROATIA' },
  { id: 'cuba', name: 'Cuba', iso3: 'CUBA' },
  { id: 'cyprus', name: 'Cyprus', iso3: 'CYPRUS' },
  { id: 'czechia', name: 'Czechia', iso3: 'CZECHIA' },
  { id: 'democratic-republic-of-the-congo', name: 'Democratic Republic of the Congo', iso3: 'DEMOCRATIC-REPUBLIC-OF-THE-CONGO' },
  { id: 'denmark', name: 'Denmark', iso3: 'DENMARK' },
  { id: 'djibouti', name: 'Djibouti', iso3: 'DJIBOUTI' },
  { id: 'dominican-republic', name: 'Dominican Republic', iso3: 'DOMINICAN-REPUBLIC' },
  { id: 'ecuador', name: 'Ecuador', iso3: 'ECUADOR' },
  { id: 'egypt', name: 'Egypt', iso3: 'EGYPT' },
  { id: 'el-salvador', name: 'El Salvador', iso3: 'EL-SALVADOR' },
  { id: 'equatorial-guinea', name: 'Equatorial Guinea', iso3: 'EQUATORIAL-GUINEA' },
  { id: 'eritrea', name: 'Eritrea', iso3: 'ERITREA' },
  { id: 'estonia', name: 'Estonia', iso3: 'ESTONIA' },
  { id: 'eswatini', name: 'Eswatini', iso3: 'ESWATINI' },
  { id: 'ethiopia', name: 'Ethiopia', iso3: 'ETHIOPIA' },
  { id: 'fiji', name: 'Fiji', iso3: 'FIJI' },
  { id: 'finland', name: 'Finland', iso3: 'FINLAND' },
  { id: 'france', name: 'France', iso3: 'FRANCE' },
  { id: 'gabon', name: 'Gabon', iso3: 'GABON' },
  { id: 'georgia', name: 'Georgia', iso3: 'GEORGIA' },
  { id: 'german-democratic-republic', name: 'German Democratic Republic', iso3: 'GERMAN-DEMOCRATIC-REPUBLIC' },
  { id: 'germany', name: 'Germany', iso3: 'GERMANY' },
  { id: 'ghana', name: 'Ghana', iso3: 'GHANA' },
  { id: 'greece', name: 'Greece', iso3: 'GREECE' },
  { id: 'guatemala', name: 'Guatemala', iso3: 'GUATEMALA' },
  { id: 'guinea', name: 'Guinea', iso3: 'GUINEA' },
  { id: 'guinea-bissau', name: 'Guinea-Bissau', iso3: 'GUINEA-BISSAU' },
  { id: 'guyana', name: 'Guyana', iso3: 'GUYANA' },
  { id: 'haiti', name: 'Haiti', iso3: 'HAITI' },
  { id: 'hamburg', name: 'Hamburg', iso3: 'HAMBURG' },
  { id: 'hanover', name: 'Hanover', iso3: 'HANOVER' },
  { id: 'hesse-darmstadt', name: 'Hesse-Darmstadt', iso3: 'HESSE-DARMSTADT' },
  { id: 'hesse-kassel', name: 'Hesse-Kassel', iso3: 'HESSE-KASSEL' },
  { id: 'honduras', name: 'Honduras', iso3: 'HONDURAS' },
  { id: 'hong-kong', name: 'Hong Kong', iso3: 'HONG-KONG' },
  { id: 'hungary', name: 'Hungary', iso3: 'HUNGARY' },
  { id: 'iceland', name: 'Iceland', iso3: 'ICELAND' },
  { id: 'india', name: 'India', iso3: 'INDIA' },
  { id: 'indonesia', name: 'Indonesia', iso3: 'INDONESIA' },
  { id: 'iran', name: 'Iran', iso3: 'IRAN' },
  { id: 'iraq', name: 'Iraq', iso3: 'IRAQ' },
  { id: 'ireland', name: 'Ireland', iso3: 'IRELAND' },
  { id: 'israel', name: 'Israel', iso3: 'ISRAEL' },
  { id: 'italy', name: 'Italy', iso3: 'ITALY' },
  { id: 'ivory-coast', name: 'Ivory Coast', iso3: 'IVORY-COAST' },
  { id: 'jamaica', name: 'Jamaica', iso3: 'JAMAICA' },
  { id: 'japan', name: 'Japan', iso3: 'JAPAN' },
  { id: 'jordan', name: 'Jordan', iso3: 'JORDAN' },
  { id: 'kazakhstan', name: 'Kazakhstan', iso3: 'KAZAKHSTAN' },
  { id: 'kenya', name: 'Kenya', iso3: 'KENYA' },
  { id: 'kosovo', name: 'Kosovo', iso3: 'KOSOVO' },
  { id: 'kuwait', name: 'Kuwait', iso3: 'KUWAIT' },
  { id: 'kyrgyzstan', name: 'Kyrgyzstan', iso3: 'KYRGYZSTAN' },
  { id: 'laos', name: 'Laos', iso3: 'LAOS' },
  { id: 'latvia', name: 'Latvia', iso3: 'LATVIA' },
  { id: 'lebanon', name: 'Lebanon', iso3: 'LEBANON' },
  { id: 'lesotho', name: 'Lesotho', iso3: 'LESOTHO' },
  { id: 'liberia', name: 'Liberia', iso3: 'LIBERIA' },
  { id: 'libya', name: 'Libya', iso3: 'LIBYA' },
  { id: 'lithuania', name: 'Lithuania', iso3: 'LITHUANIA' },
  { id: 'luxembourg', name: 'Luxembourg', iso3: 'LUXEMBOURG' },
  { id: 'madagascar', name: 'Madagascar', iso3: 'MADAGASCAR' },
  { id: 'malawi', name: 'Malawi', iso3: 'MALAWI' },
  { id: 'malaysia', name: 'Malaysia', iso3: 'MALAYSIA' },
  { id: 'maldives', name: 'Maldives', iso3: 'MALDIVES' },
  { id: 'mali', name: 'Mali', iso3: 'MALI' },
  { id: 'malta', name: 'Malta', iso3: 'MALTA' },
  { id: 'mauritania', name: 'Mauritania', iso3: 'MAURITANIA' },
  { id: 'mauritius', name: 'Mauritius', iso3: 'MAURITIUS' },
  { id: 'mecklenburg-schwerin', name: 'Mecklenburg Schwerin', iso3: 'MECKLENBURG-SCHWERIN' },
  { id: 'mexico', name: 'Mexico', iso3: 'MEXICO' },
  { id: 'modena', name: 'Modena', iso3: 'MODENA' },
  { id: 'moldova', name: 'Moldova', iso3: 'MOLDOVA' },
  { id: 'mongolia', name: 'Mongolia', iso3: 'MONGOLIA' },
  { id: 'montenegro', name: 'Montenegro', iso3: 'MONTENEGRO' },
  { id: 'morocco', name: 'Morocco', iso3: 'MOROCCO' },
  { id: 'mozambique', name: 'Mozambique', iso3: 'MOZAMBIQUE' },
  { id: 'namibia', name: 'Namibia', iso3: 'NAMIBIA' },
  { id: 'nassau', name: 'Nassau', iso3: 'NASSAU' },
  { id: 'nepal', name: 'Nepal', iso3: 'NEPAL' },
  { id: 'netherlands', name: 'Netherlands', iso3: 'NETHERLANDS' },
  { id: 'new-zealand', name: 'New Zealand', iso3: 'NEW-ZEALAND' },
  { id: 'nicaragua', name: 'Nicaragua', iso3: 'NICARAGUA' },
  { id: 'niger', name: 'Niger', iso3: 'NIGER' },
  { id: 'nigeria', name: 'Nigeria', iso3: 'NIGERIA' },
  { id: 'north-korea', name: 'North Korea', iso3: 'NORTH-KOREA' },
  { id: 'north-macedonia', name: 'North Macedonia', iso3: 'NORTH-MACEDONIA' },
  { id: 'norway', name: 'Norway', iso3: 'NORWAY' },
  { id: 'oldenburg', name: 'Oldenburg', iso3: 'OLDENBURG' },
  { id: 'oman', name: 'Oman', iso3: 'OMAN' },
  { id: 'pakistan', name: 'Pakistan', iso3: 'PAKISTAN' },
  { id: 'palestine-british-mandate', name: 'Palestine/British Mandate', iso3: 'PALESTINE-BRITISH-MANDATE' },
  { id: 'palestine-gaza', name: 'Palestine/Gaza', iso3: 'PALESTINE-GAZA' },
  { id: 'palestine-west-bank', name: 'Palestine/West Bank', iso3: 'PALESTINE-WEST-BANK' },
  { id: 'panama', name: 'Panama', iso3: 'PANAMA' },
  { id: 'papal-states', name: 'Papal States', iso3: 'PAPAL-STATES' },
  { id: 'papua-new-guinea', name: 'Papua New Guinea', iso3: 'PAPUA-NEW-GUINEA' },
  { id: 'paraguay', name: 'Paraguay', iso3: 'PARAGUAY' },
  { id: 'parma', name: 'Parma', iso3: 'PARMA' },
  { id: 'peru', name: 'Peru', iso3: 'PERU' },
  { id: 'philippines', name: 'Philippines', iso3: 'PHILIPPINES' },
  { id: 'piedmont-sardinia', name: 'Piedmont-Sardinia', iso3: 'PIEDMONT-SARDINIA' },
  { id: 'poland', name: 'Poland', iso3: 'POLAND' },
  { id: 'portugal', name: 'Portugal', iso3: 'PORTUGAL' },
  { id: 'qatar', name: 'Qatar', iso3: 'QATAR' },
  { id: 'republic-of-vietnam', name: 'Republic of Vietnam', iso3: 'REPUBLIC-OF-VIETNAM' },
  { id: 'republic-of-the-congo', name: 'Republic of the Congo', iso3: 'REPUBLIC-OF-THE-CONGO' },
  { id: 'romania', name: 'Romania', iso3: 'ROMANIA' },
  { id: 'russia', name: 'Russia', iso3: 'RUSSIA' },
  { id: 'rwanda', name: 'Rwanda', iso3: 'RWANDA' },
  { id: 'sao-tome-and-principe', name: 'Sao Tome and Principe', iso3: 'SAO-TOME-AND-PRINCIPE' },
  { id: 'saudi-arabia', name: 'Saudi Arabia', iso3: 'SAUDI-ARABIA' },
  { id: 'saxe-weimar-eisenach', name: 'Saxe-Weimar-Eisenach', iso3: 'SAXE-WEIMAR-EISENACH' },
  { id: 'saxony', name: 'Saxony', iso3: 'SAXONY' },
  { id: 'senegal', name: 'Senegal', iso3: 'SENEGAL' },
  { id: 'serbia', name: 'Serbia', iso3: 'SERBIA' },
  { id: 'seychelles', name: 'Seychelles', iso3: 'SEYCHELLES' },
  { id: 'sierra-leone', name: 'Sierra Leone', iso3: 'SIERRA-LEONE' },
  { id: 'singapore', name: 'Singapore', iso3: 'SINGAPORE' },
  { id: 'slovakia', name: 'Slovakia', iso3: 'SLOVAKIA' },
  { id: 'slovenia', name: 'Slovenia', iso3: 'SLOVENIA' },
  { id: 'solomon-islands', name: 'Solomon Islands', iso3: 'SOLOMON-ISLANDS' },
  { id: 'somalia', name: 'Somalia', iso3: 'SOMALIA' },
  { id: 'somaliland', name: 'Somaliland', iso3: 'SOMALILAND' },
  { id: 'south-africa', name: 'South Africa', iso3: 'SOUTH-AFRICA' },
  { id: 'south-korea', name: 'South Korea', iso3: 'SOUTH-KOREA' },
  { id: 'south-sudan', name: 'South Sudan', iso3: 'SOUTH-SUDAN' },
  { id: 'south-yemen', name: 'South Yemen', iso3: 'SOUTH-YEMEN' },
  { id: 'spain', name: 'Spain', iso3: 'SPAIN' },
  { id: 'sri-lanka', name: 'Sri Lanka', iso3: 'SRI-LANKA' },
  { id: 'sudan', name: 'Sudan', iso3: 'SUDAN' },
  { id: 'suriname', name: 'Suriname', iso3: 'SURINAME' },
  { id: 'sweden', name: 'Sweden', iso3: 'SWEDEN' },
  { id: 'switzerland', name: 'Switzerland', iso3: 'SWITZERLAND' },
  { id: 'syria', name: 'Syria', iso3: 'SYRIA' },
  { id: 'taiwan', name: 'Taiwan', iso3: 'TAIWAN' },
  { id: 'tajikistan', name: 'Tajikistan', iso3: 'TAJIKISTAN' },
  { id: 'tanzania', name: 'Tanzania', iso3: 'TANZANIA' },
  { id: 'thailand', name: 'Thailand', iso3: 'THAILAND' },
  { id: 'the-gambia', name: 'The Gambia', iso3: 'THE-GAMBIA' },
  { id: 'timor-leste', name: 'Timor-Leste', iso3: 'TIMOR-LESTE' },
  { id: 'togo', name: 'Togo', iso3: 'TOGO' },
  { id: 'trinidad-and-tobago', name: 'Trinidad and Tobago', iso3: 'TRINIDAD-AND-TOBAGO' },
  { id: 'tunisia', name: 'Tunisia', iso3: 'TUNISIA' },
  { id: 'turkmenistan', name: 'Turkmenistan', iso3: 'TURKMENISTAN' },
  { id: 'tuscany', name: 'Tuscany', iso3: 'TUSCANY' },
  { id: 'two-sicilies', name: 'Two Sicilies', iso3: 'TWO-SICILIES' },
  { id: 'turkiye', name: 'Türkiye', iso3: 'TURKIYE' },
  { id: 'uganda', name: 'Uganda', iso3: 'UGANDA' },
  { id: 'ukraine', name: 'Ukraine', iso3: 'UKRAINE' },
  { id: 'united-arab-emirates', name: 'United Arab Emirates', iso3: 'UNITED-ARAB-EMIRATES' },
  { id: 'united-kingdom', name: 'United Kingdom', iso3: 'UNITED-KINGDOM' },
  { id: 'united-states-of-america', name: 'United States of America', iso3: 'UNITED-STATES-OF-AMERICA' },
  { id: 'uruguay', name: 'Uruguay', iso3: 'URUGUAY' },
  { id: 'uzbekistan', name: 'Uzbekistan', iso3: 'UZBEKISTAN' },
  { id: 'vanuatu', name: 'Vanuatu', iso3: 'VANUATU' },
  { id: 'venezuela', name: 'Venezuela', iso3: 'VENEZUELA' },
  { id: 'vietnam', name: 'Vietnam', iso3: 'VIETNAM' },
  { id: 'wurtemberg', name: 'Würtemberg', iso3: 'WURTEMBERG' },
  { id: 'yemen', name: 'Yemen', iso3: 'YEMEN' },
  { id: 'zambia', name: 'Zambia', iso3: 'ZAMBIA' },
  { id: 'zanzibar', name: 'Zanzibar', iso3: 'ZANZIBAR' },
  { id: 'zimbabwe', name: 'Zimbabwe', iso3: 'ZIMBABWE' }
];

export function getCountryById(id: string): Country | undefined {
  return COUNTRIES.find(c => c.id === id);
}

export function searchCountries(query: string): Country[] {
  const lowercaseQuery = query.toLowerCase();
  return COUNTRIES.filter(c => 
    c.name.toLowerCase().includes(lowercaseQuery) ||
    c.id.toLowerCase().includes(lowercaseQuery)
  );
}