// Codes to hide from the sidebar menus (variables removed from UI)
export const HIDDEN_VARIABLE_CODES = new Set<string>([
  'v2ellocnam',
  'v2elregnam',
  'v2exnamhog',
  'v2exnamhos',
  'v2exparhos',
  'v2expothog',
  'v2extithog',
  'v2extithos',
  'v2juhcname',
  'v2lgnamelo',
  'v2lgnameup',
  'v2lpname',
  'v2reginfo',
  'v2slpname',
  'v2tlpname',
  'v3ellocnam',
  'v3elregnam',
  'v3exnamhog',
  'v3exnamhos',
  'v3extithog',
  'v3extithos',
  'v3juhcname',
  'v3lgcamoth',
  'v3lgnamelo',
  'v3lgnameup',
]);
