// IMF dataset code mappings (WEO and NEA)
// Provided mapping: code -> human readable description
// We also build reverse maps (description -> code) to allow lookup by label.

// NOTE: Keep these objects flat; later we can split or lazy load if size grows.
export const IMF_WEO_CODE_TO_DESC: Record<string, string> = {
  "BCA.A": "Current account balance (credit less debit), US dollar",
  "BCA_NGDPD.A": "Current account balance (credit less debit), Percent of GDP",
  "BF.A": "Financial account balance (assets less liabilities), US dollar",
  "BFD.A": "Direct investment, Net (assets minus liabilities), US dollar",
  "BFF.A": "Financial derivatives and employee stock options, Net (assets minus liabilities), US dollar",
  "BFO.A": "Other investment, Net (assets minus liabilities), US dollar",
  "BFP.A": "Portfolio investment, Net (assets minus liabilities), US dollar",
  "BFRA.A": "Change in reserve assets, Net (assets minus liabilities), US dollar",
  "BM.A": "Imports of goods and services, US dollar",
  "BX.A": "Exports of goods and services, US dollar",
  "D.A": "External debt, US dollar",
  "DS.A": "External debt: total debt service, US dollar",
  "DSI.A": "External debt: total debt service, interest, US dollar",
  "DSI_BX.A": "External debt: total debt service, interest, Percent of exports of goods and services",
  "DSI_NGDPD.A": "External debt: total debt service, interest, Percent of GDP",
  "DSP.A": "External debt: total debt service, amortization, US dollar",
  "DSP_BX.A": "External debt: total debt service, amortization, Percent of exports of goods and services",
  "DSP_NGDPD.A": "External debt: total debt service, amortization, Percent of GDP",
  "DS_BX.A": "External debt: total debt service, Percent of exports of goods and services",
  "DS_NGDPD.A": "External debt: total debt service, Percent of GDP",
  "D_BX.A": "External debt, Percent of exports of goods and services",
  "D_NGDPD.A": "External debt, Percent of GDP",
  "GGR.A": "Revenue, General government, Domestic currency",
  "GGR_NGDP.A": "Revenue, General government, Percent of GDP",
  "GGSB.A": "Structural balance, General government, Domestic currency",
  "GGSB_NPGDP.A": "Structural balance, General government, Percent",
  "GGX.A": "Expenditure, General government, Domestic currency",
  "GGXCNL.A": "Net lending (+) / net borrowing (-), General government, Domestic currency",
  "GGXCNL_NGDP.A": "Net lending (+) / net borrowing (-), General government, Percent of GDP",
  "GGXONLB.A": "Primary net lending (+) / net borrowing (-), General government, Domestic currency",
  "GGXONLB_NGDP.A": "Primary net lending (+) / net borrowing (-), General government, Percent of GDP",
  "GGXWDG.A": "Gross debt, General government, Domestic currency",
  "GGXWDG_NGDP.A": "Gross debt, General government, Percent of GDP",
  "GGXWDN.A": "Net debt, General government, Domestic currency",
  "GGXWDN_NGDP.A": "Net debt, General government, Percent of GDP",
  "GGX_NGDP.A": "Expenditure, General government, Percent of GDP",
  "LE.A": "Employed persons, Persons for countries / Index for country groups",
  "LP.A": "Population, Persons for countries / Index for country groups",
  "LUR.A": "Unemployment rate",
  "NGAP_NPGDP.A": "Output gap, Percent of potential GDP",
  "NGDP.A": "Gross domestic product (GDP), Current prices, Domestic currency",
  "NGDPD.A": "Gross domestic product (GDP), Current prices, US dollar",
  "NGDPDPC.A": "Gross domestic product (GDP), Current prices, Per capita, US dollar",
  "NGDPPC.A": "Gross domestic product (GDP), Current prices, Per capita, Domestic currency",
  "NGDPRPC.A": "Gross domestic product (GDP), Constant prices, Per capita, Domestic currency",
  "NGDPRPPPPC.A": "Gross domestic product (GDP), Constant prices, Per capita, purchasing power parity (PPP) international dollar, ICP benchmark 2021",
  "NGDP_D.A": "Gross domestic product (GDP), Price deflator, Index",
  "NGDP_FY.A": "Gross domestic product (GDP), Current prices, Fiscal year, Domestic currency",
  "NGDP_R.A": "Gross domestic product (GDP), Constant prices, Domestic currency",
  "NGDP_RPCH.A": "Gross domestic product (GDP), Constant prices, Percent change",
  "NGDP_RPCHMK.A": "Gross domestic product (GDP), Constant prices, Percent",
  "NGSD_NGDP.A": "Gross national savings, Percent of GDP",
  "NID_NGDP.A": "Gross capital formation, Percent of GDP",
  "PALLFNFW.A": "All commodities, Commodity price index",
  "PALUM.A": "Aluminum, Unit prices, US dollars per metric tonne",
  "PBANSOP.A": "Bananas, Unit prices, US dollars per metric tonne",
  "PBARL.A": "Barley, Unit prices, US dollars per metric tonne",
  "PBEEF.A": "Beef, Import price, US cents per pound",
  "PBEVEW.A": "Beverages, Commodity price index",
  "PCEREW.A": "Cereal, Commodity price index",
  "PCOALAU.A": "Coal, Australia, Unit prices, US dollars per metric tonne",
  "PCOALSA.A": "Coal, South Africa, Export price, US dollars per metric tonne",
  "PCOALW.A": "Coal, Commodity price index",
  "PCOCO.A": "Cocoa, Unit prices, US dollars per metric tonne",
  "PCOFFOTM.A": "Coffee, other mild Arabica, Unit prices, US cents per pound",
  "PCOFFROB.A": "Coffee, Robustas, Unit prices, US cents per pound",
  "PCOFFW.A": "Coffee, Commodity price index",
  "PCOPP.A": "Copper, Unit prices, US dollars per metric tonne",
  "PCOTTIND.A": "Cotton, Unit prices, US cents per pound",
  "PCPI.A": "All Items, Consumer price index (CPI), Period average",
  "PCPIE.A": "All Items, Consumer price index (CPI), End-of-period (EoP)",
  "PCPIEPCH.A": "All Items, Consumer price index (CPI), End-of-period (EoP), percent change",
  "PCPIPCH.A": "All Items, Consumer price index (CPI), Period average, percent change",
  "PFANDBW.A": "Food and beverage, Commodity price index",
  "PFISH.A": "Fishmeal, Unit prices, US dollars per metric tonne",
  "PFOODW.A": "Food, Commodity price index",
  "PGNUTS.A": "Groundnuts, Unit prices, US dollars per metric tonne",
  "PHARDW.A": "Hardwood, Commodity price index",
  "PHIDE.A": "Hides, Unit prices, US cents per pound",
  "PINDUW.A": "Industrial materials, Commodity price index",
  "PIORECR.A": "Iron ore, Unit prices, US dollars per metric tonne",
  "PLAMB.A": "Lamb, Unit prices, US cents per pound",
  "PLEAD.A": "Lead, Unit prices, US dollars per metric tonne",
  "PLOGORE.A": "Soft logs, Export price, US dollars per cubic meter",
  "PLOGSK.A": "Hard logs, import price Japan, Import price, US dollars per cubic meter",
  "PMAIZMT.A": "Corn, Unit prices, US dollars per metric tonne",
  "PMEATW.A": "Meat, Commodity price index",
  "PMETAW.A": "Metal, Commodity price index",
  "PNFUELW.A": "Non-fuel, Commodity price index",
  "PNGASEU.A": "Natural gas, EU, Unit prices, US dollars per million metric British thermal units of gas",
  "PNGASJP.A": "LNG, Asia, Unit prices, US dollars per million metric British thermal units of gas",
  "PNGASUS.A": "Natural Gas, US Henry Hub Gas, Unit prices, US dollars per metric tonne",
  "PNGASW.A": "Natural gas, Commodity price index",
  "PNICK.A": "Nickel, Unit prices, US dollars per metric tonne",
  "PNRGW.A": "Energy, Commodity price index",
  "POILAPSP.A": "APSP crude oil, Unit prices, US dollars per barrel",
  "POILAPSPW.A": "APSP crude oil, Commodity price index",
  "POILBRE.A": "Brent crude, Unit prices, US dollars per barrel",
  "POILDUB.A": "Dubai crude, Unit prices, US dollars per barrel",
  "POILWTI.A": "WTI crude, Unit prices, US dollars per barrel",
  "POLVOIL.A": "Olive oil, Unit prices, US dollars per metric tonne",
  "PORANG.A": "Orange, Import price, US dollars per metric tonne",
  "PPOIL.A": "Palm oil, Unit prices, US dollars per metric tonne",
  "PPORK.A": "Swine, Unit prices, US cents per pound",
  "PPOULT.A": "Poultry, Unit prices, US cents per pound",
  "PPPEX.A": "Rate, Domestic currency per international dollar in PPP terms, ICP benchmarks 2017-2021",
  "PPPGDP.A": "Gross domestic product (GDP), Current prices, Purchasing power parity (PPP) international dollar, ICP benchmarks 2017-2021",
  "PPPPC.A": "Gross domestic product (GDP), Per capita, purchasing power parity (PPP) international dollar, ICP benchmarks 2017-2021",
  "PPPSH.A": "Gross domestic product (GDP), Purchasing power parity (PPP) international dollar, percent of world GDP, Percent, ICP benchmarks 2017-2021",
  "PRAWMW.A": "Agricultural raw materials, Commodity price index",
  "PRICENPQ.A": "Rice, Thailand, Unit prices, US dollars per metric tonne",
  "PROIL.A": "Rapeseed oil, Unit prices, US dollars per metric tonne",
  "PRUBB.A": "Rubber, Unit prices, US cents per pound",
  "PSALM.A": "Fish, Export price, US dollars per kilogram",
  "PSAWMAL.A": "Hard sawnwood, Dark Red Meranti, Unit prices, US dollars per cubic meter",
  "PSAWORE.A": "Soft sawnwood, Export price, US dollars per cubic meter",
  "PSEAFW.A": "Seafood, Commodity price index",
  "PSHRI.A": "Shrimp, Unit prices, US dollars per kilogram",
  "PSMEA.A": "Soybean meal, Unit prices, US dollars per metric tonne",
  "PSOFTW.A": "Softwood, Commodity price index",
  "PSOIL.A": "Soybeans oil, Unit prices, US dollars per metric tonne",
  "PSOYB.A": "Soybeans, Unit prices, US dollars per metric tonne",
  "PSUGAISA.A": "Sugar, No. 11, World, Unit prices, US cents per pound",
  "PSUGAUSA.A": "Sugar, No. 16, US, Import price, US cents per pound",
  "PSUGAW.A": "Sugar, Commodity price index",
  "PSUNO.A": "Sunflower oil, Export price, US dollars per metric tonne",
  "PTEA.A": "Tea, Kenyan, Unit prices, US cents per kilogram",
  "PTIMBW.A": "Timber, Commodity price index",
  "PTIN.A": "Tin, Unit prices, US dollars per metric tonne",
  "PURAN.A": "Uranium, Unit prices, US dollars per pound",
  "PVOILW.A": "Vegetable oil, Commodity price index",
  "PWHEAMT.A": "Wheat, Unit prices, US dollars per metric tonne",
  "PWOOLC.A": "Wool, coarse, Unit prices, US cents per kilogram",
  "PWOOLF.A": "Wool, fine, Unit prices, US cents per kilogram",
  "PWOOLW.A": "Wool, Commodity price index",
  "PZINC.A": "Zinc, Unit prices, US dollars per metric tonne",
  "TMG_RPCH.A": "Imports of goods, Volume, Cost insurance freight (CIF), Percent change",
  "TM_RPCH.A": "Imports of goods and services, Volume, Cost insurance freight (CIF), Percent change",
  "TRADEPCH.A": "Trade of goods and services, Volume, Percent change",
  "TTPCH.A": "Terms of trade of goods and services, percent change",
  "TTTPCH.A": "Terms of trade of goods, percent change",
  "TXGM_D.A": "Exports of manufactures, Price deflator, Free on board (FOB), Index",
  "TXGM_DPCH.A": "Exports of manufactures, Price deflator, Free on board (FOB), Percent change",
  "TXG_RPCH.A": "Exports of goods, Volume, Free on board (FOB), Percent change",
  "TX_RPCH.A": "Exports of goods and services, Volume, Free on board (FOB), Percent change"
};

export const IMF_NEA_CODE_TO_DESC: Record<string, string> = {
  "B11.Q.USD.A": "External balance of goods and services",
  "B11.Q.XDC.A": "External balance of goods and services",
  "B11.V.USD.A": "External balance of goods and services",
  "B11.V.XDC.A": "External balance of goods and services",
  "B1G.Q.USD.A": "Gross value added (GVA)",
  "B1G.Q.XDC.A": "Gross value added (GVA)",
  "B1G.V.USD.A": "Gross value added (GVA)",
  "B1G.V.XDC.A": "Gross value added (GVA)",
  "B1GQ.PD.IX.A": "Gross domestic product (GDP)",
  "B1GQ.Q.USD.A": "Gross domestic product (GDP)",
  "B1GQ.Q.XDC.A": "Gross domestic product (GDP)",
  "B1GQ.V.USD.A": "Gross domestic product (GDP)",
  "B1GQ.V.XDC.A": "Gross domestic product (GDP)",
  "B1GQPA.Q.USD.A": "Gross domestic product (GDP) production approach",
  "B1GQPA.Q.XDC.A": "Gross domestic product (GDP) production approach",
  "B1GQPA.V.USD.A": "Gross domestic product (GDP) production approach",
  "B1GQPA.V.XDC.A": "Gross domestic product (GDP) production approach",
  "B1G_A.Q.USD.A": "Gross value added (GVA), Agriculture, forestry and fishing",
  "B1G_A.Q.XDC.A": "Gross value added (GVA), Agriculture, forestry and fishing",
  "B1G_A.V.USD.A": "Gross value added (GVA), Agriculture, forestry and fishing",
  "B1G_A.V.XDC.A": "Gross value added (GVA), Agriculture, forestry and fishing",
  "B1G_B.Q.USD.A": "Gross value added (GVA), Mining and quarrying",
  "B1G_B.Q.XDC.A": "Gross value added (GVA), Mining and quarrying",
  "B1G_B.V.USD.A": "Gross value added (GVA), Mining and quarrying",
  "B1G_B.V.XDC.A": "Gross value added (GVA), Mining and quarrying",
  "B1G_C.Q.USD.A": "Gross value added (GVA), Manufacturing",
  "B1G_C.Q.XDC.A": "Gross value added (GVA), Manufacturing",
  "B1G_C.V.USD.A": "Gross value added (GVA), Manufacturing",
  "B1G_C.V.XDC.A": "Gross value added (GVA), Manufacturing",
  "B1G_D35.Q.USD.A": "Gross value added (GVA), Electricity, gas, steam and air conditioning supply",
  "B1G_D35.Q.XDC.A": "Gross value added (GVA), Electricity, gas, steam and air conditioning supply",
  "B1G_D35.V.USD.A": "Gross value added (GVA), Electricity, gas, steam and air conditioning supply",
  "B1G_D35.V.XDC.A": "Gross value added (GVA), Electricity, gas, steam and air conditioning supply",
  "B1G_E.Q.USD.A": "Gross value added (GVA), Water supply; sewerage, waste management and remediation activities",
  "B1G_E.Q.XDC.A": "Gross value added (GVA), Water supply; sewerage, waste management and remediation activities",
  "B1G_E.V.USD.A": "Gross value added (GVA), Water supply; sewerage, waste management and remediation activities",
  "B1G_E.V.XDC.A": "Gross value added (GVA), Water supply; sewerage, waste management and remediation activities",
  "B1G_F.Q.USD.A": "Gross value added (GVA), Construction",
  "B1G_F.Q.XDC.A": "Gross value added (GVA), Construction",
  "B1G_F.V.USD.A": "Gross value added (GVA), Construction",
  "B1G_F.V.XDC.A": "Gross value added (GVA), Construction",
  "B1G_G.Q.USD.A": "Gross value added (GVA), Wholesale and retail trade; repair of motor vehicles and motorcycles",
  "B1G_G.Q.XDC.A": "Gross value added (GVA), Wholesale and retail trade; repair of motor vehicles and motorcycles",
  "B1G_G.V.USD.A": "Gross value added (GVA), Wholesale and retail trade; repair of motor vehicles and motorcycles",
  "B1G_G.V.XDC.A": "Gross value added (GVA), Wholesale and retail trade; repair of motor vehicles and motorcycles",
  "B1G_H.Q.USD.A": "Gross value added (GVA), Transportation and storage",
  "B1G_H.Q.XDC.A": "Gross value added (GVA), Transportation and storage",
  "B1G_H.V.USD.A": "Gross value added (GVA), Transportation and storage",
  "B1G_H.V.XDC.A": "Gross value added (GVA), Transportation and storage",
  "B1G_I.Q.USD.A": "Gross value added (GVA), Accommodation and food service activities",
  "B1G_I.Q.XDC.A": "Gross value added (GVA), Accommodation and food service activities",
  "B1G_I.V.USD.A": "Gross value added (GVA), Accommodation and food service activities",
  "B1G_I.V.XDC.A": "Gross value added (GVA), Accommodation and food service activities",
  "B1G_INDE.Q.USD.A": "Gross value added (GVA), Industry and water supply",
  "B1G_INDE.Q.XDC.A": "Gross value added (GVA), Industry and water supply",
  "B1G_INDE.V.USD.A": "Gross value added (GVA), Industry and water supply",
  "B1G_INDE.V.XDC.A": "Gross value added (GVA), Industry and water supply",
  "B1G_INDF.Q.USD.A": "Gross value added (GVA), Industry and construction",
  "B1G_INDF.Q.XDC.A": "Gross value added (GVA), Industry and construction",
  "B1G_INDF.V.USD.A": "Gross value added (GVA), Industry and construction",
  "B1G_INDF.V.XDC.A": "Gross value added (GVA), Industry and construction",
  "B1G_J.Q.USD.A": "Gross value added (GVA), Information and communication",
  "B1G_J.Q.XDC.A": "Gross value added (GVA), Information and communication",
  "B1G_J.V.USD.A": "Gross value added (GVA), Information and communication",
  "B1G_J.V.XDC.A": "Gross value added (GVA), Information and communication",
  "B1G_K.Q.USD.A": "Gross value added (GVA), Financial and insurance activities",
  "B1G_K.Q.XDC.A": "Gross value added (GVA), Financial and insurance activities",
  "B1G_K.V.USD.A": "Gross value added (GVA), Financial and insurance activities",
  "B1G_K.V.XDC.A": "Gross value added (GVA), Financial and insurance activities",
  "B1G_L68.Q.USD.A": "Gross value added (GVA), Real estate activities",
  "B1G_L68.Q.XDC.A": "Gross value added (GVA), Real estate activities",
  "B1G_L68.V.USD.A": "Gross value added (GVA), Real estate activities",
  "B1G_L68.V.XDC.A": "Gross value added (GVA), Real estate activities",
  "B1G_M.Q.USD.A": "Gross value added (GVA), Professional, scientific and technical activities",
  "B1G_M.Q.XDC.A": "Gross value added (GVA), Professional, scientific and technical activities",
  "B1G_M.V.USD.A": "Gross value added (GVA), Professional, scientific and technical activities",
  "B1G_M.V.XDC.A": "Gross value added (GVA), Professional, scientific and technical activities",
  "B1G_N.Q.USD.A": "Gross value added (GVA), Administrative and support service activities",
  "B1G_N.Q.XDC.A": "Gross value added (GVA), Administrative and support service activities",
  "B1G_N.V.USD.A": "Gross value added (GVA), Administrative and support service activities",
  "B1G_N.V.XDC.A": "Gross value added (GVA), Administrative and support service activities",
  "B1G_O84.Q.USD.A": "Gross value added (GVA), Public administration and defence; compulsory social security",
  "B1G_O84.Q.XDC.A": "Gross value added (GVA), Public administration and defence; compulsory social security",
  "B1G_O84.V.USD.A": "Gross value added (GVA), Public administration and defence; compulsory social security",
  "B1G_O84.V.XDC.A": "Gross value added (GVA), Public administration and defence; compulsory social security",
  "B1G_OTQ.Q.USD.A": "Gross value added (GVA), Public administration, defence, education, human health and social work activities",
  "B1G_OTQ.Q.XDC.A": "Gross value added (GVA), Public administration, defence, education, human health and social work activities",
  "B1G_OTQ.V.USD.A": "Gross value added (GVA), Public administration, defence, education, human health and social work activities",
  "B1G_OTQ.V.XDC.A": "Gross value added (GVA), Public administration, defence, education, human health and social work activities",
  "B1G_P85.Q.USD.A": "Gross value added (GVA), Education",
  "B1G_P85.Q.XDC.A": "Gross value added (GVA), Education",
  "B1G_P85.V.USD.A": "Gross value added (GVA), Education",
  "B1G_P85.V.XDC.A": "Gross value added (GVA), Education",
  "B1G_P85HHSW.Q.USD.A": "Gross value added (GVA), Education, human health and social work",
  "B1G_P85HHSW.Q.XDC.A": "Gross value added (GVA), Education, human health and social work",
  "B1G_P85HHSW.V.USD.A": "Gross value added (GVA), Education, human health and social work",
  "B1G_P85HHSW.V.XDC.A": "Gross value added (GVA), Education, human health and social work",
  "B1G_Q.Q.USD.A": "Gross value added (GVA), Human health and social work activities",
  "B1G_Q.Q.XDC.A": "Gross value added (GVA), Human health and social work activities",
  "B1G_Q.V.USD.A": "Gross value added (GVA), Human health and social work activities",
  "B1G_Q.V.XDC.A": "Gross value added (GVA), Human health and social work activities",
  "B1G_R.Q.USD.A": "Gross value added (GVA), Arts, entertainment and recreation",
  "B1G_R.Q.XDC.A": "Gross value added (GVA), Arts, entertainment and recreation",
  "B1G_R.V.USD.A": "Gross value added (GVA), Arts, entertainment and recreation",
  "B1G_R.V.XDC.A": "Gross value added (GVA), Arts, entertainment and recreation",
  "B1G_RTU.Q.USD.A": "Gross value added (GVA), Other services",
  "B1G_RTU.Q.XDC.A": "Gross value added (GVA), Other services",
  "B1G_RTU.V.USD.A": "Gross value added (GVA), Other services",
  "B1G_RTU.V.XDC.A": "Gross value added (GVA), Other services",
  "B1G_S.Q.USD.A": "Gross value added (GVA), Other service activities",
  "B1G_S.Q.XDC.A": "Gross value added (GVA), Other service activities",
  "B1G_S.V.USD.A": "Gross value added (GVA), Other service activities",
  "B1G_S.V.XDC.A": "Gross value added (GVA), Other service activities",
  "B1G_T9700.Q.USD.A": "Gross value added (GVA), Activities of households as employers of domestic personnel",
  "B1G_T9700.Q.XDC.A": "Gross value added (GVA), Activities of households as employers of domestic personnel",
  "B1G_T9700.V.USD.A": "Gross value added (GVA), Activities of households as employers of domestic personnel",
  "B1G_T9700.V.XDC.A": "Gross value added (GVA), Activities of households as employers of domestic personnel",
  "B1G_U9900.Q.USD.A": "Gross value added (GVA), Activities of extraterritorial organizations and bodies",
  "B1G_U9900.Q.XDC.A": "Gross value added (GVA), Activities of extraterritorial organizations and bodies",
  "B1G_U9900.V.USD.A": "Gross value added (GVA), Activities of extraterritorial organizations and bodies",
  "B1G_U9900.V.XDC.A": "Gross value added (GVA), Activities of extraterritorial organizations and bodies",
  "D21.Q.USD.A": "Taxes on products",
  "D21.Q.XDC.A": "Taxes on products",
  "D21.V.USD.A": "Taxes on products",
  "D21.V.XDC.A": "Taxes on products",
  "D29X39.Q.USD.A": "Net taxes on production",
  "D29X39.Q.XDC.A": "Net taxes on production",
  "D29X39.V.USD.A": "Net taxes on production",
  "D29X39.V.XDC.A": "Net taxes on production",
  "D31.Q.USD.A": "Subsidies on products",
  "D31.Q.XDC.A": "Subsidies on products",
  "D31.V.USD.A": "Subsidies on products",
  "D31.V.XDC.A": "Subsidies on products",
  "N111N.Q.USD.A": "Acquisitions less disposals of fixed assets: residential structures",
  "N111N.Q.XDC.A": "Acquisitions less disposals of fixed assets: residential structures",
  "N111N.V.USD.A": "Acquisitions less disposals of fixed assets: residential structures",
  "N111N.V.XDC.A": "Acquisitions less disposals of fixed assets: residential structures",
  "N1121N.Q.USD.A": "Acquisitions less disposals of fixed assets non-residential structures",
  "N1121N.Q.XDC.A": "Acquisitions less disposals of fixed assets non-residential structures",
  "N1121N.V.USD.A": "Acquisitions less disposals of fixed assets non-residential structures",
  "N1121N.V.XDC.A": "Acquisitions less disposals of fixed assets non-residential structures",
  "P3.Q.USD.A": "Final consumption expenditure",
  "P3.Q.XDC.A": "Final consumption expenditure",
  "P3.V.USD.A": "Final consumption expenditure",
  "P3.V.XDC.A": "Final consumption expenditure",
  "P31_S13.Q.USD.A": "Individual consumption expenditure, General government",
  "P31_S13.Q.XDC.A": "Individual consumption expenditure, General government",
  "P31_S13.V.USD.A": "Individual consumption expenditure, General government",
  "P31_S13.V.XDC.A": "Individual consumption expenditure, General government",
  "P32_S13.Q.USD.A": "Collective consumption expenditure, General government",
  "P32_S13.Q.XDC.A": "Collective consumption expenditure, General government",
  "P32_S13.V.USD.A": "Collective consumption expenditure, General government",
  "P32_S13.V.XDC.A": "Collective consumption expenditure, General government",
  "P3_PS.Q.USD.A": "Final consumption expenditure, Private sector",
  "P3_PS.Q.XDC.A": "Final consumption expenditure, Private sector",
  "P3_PS.V.USD.A": "Final consumption expenditure, Private sector",
  "P3_PS.V.XDC.A": "Final consumption expenditure, Private sector",
  "P3_S13.Q.USD.A": "Final consumption expenditure, General government",
  "P3_S13.Q.XDC.A": "Final consumption expenditure, General government",
  "P3_S13.V.USD.A": "Final consumption expenditure, General government",
  "P3_S13.V.XDC.A": "Final consumption expenditure, General government",
  "P3_S14.Q.USD.A": "Final consumption expenditure, Households",
  "P3_S14.Q.XDC.A": "Final consumption expenditure, Households",
  "P3_S14.V.USD.A": "Final consumption expenditure, Households",
  "P3_S14.V.XDC.A": "Final consumption expenditure, Households",
  "P3_S15.Q.USD.A": "Final consumption expenditure, Non profit institutions serving households",
  "P3_S15.Q.XDC.A": "Final consumption expenditure, Non profit institutions serving households",
  "P3_S15.V.USD.A": "Final consumption expenditure, Non profit institutions serving households",
  "P3_S15.V.XDC.A": "Final consumption expenditure, Non profit institutions serving households",
  "P3_S1M.V.XDC.A": "Final consumption expenditure, Households and non profit institutions serving households (NPISH)",
  "P5.Q.USD.A": "Gross capital formation",
  "P5.Q.XDC.A": "Gross capital formation",
  "P5.V.USD.A": "Gross capital formation",
  "P5.V.XDC.A": "Gross capital formation",
  "P511N113N.Q.USD.A": "Acquisitions less disposals of fixed assets: machinery and equipment",
  "P511N113N.Q.XDC.A": "Acquisitions less disposals of fixed assets: machinery and equipment",
  "P511N113N.V.USD.A": "Acquisitions less disposals of fixed assets: machinery and equipment",
  "P511N113N.V.XDC.A": "Acquisitions less disposals of fixed assets: machinery and equipment",
  "P51G.Q.USD.A": "Gross fixed capital formation",
  "P51G.Q.XDC.A": "Gross fixed capital formation",
  "P51G.V.USD.A": "Gross fixed capital formation",
  "P51G.V.XDC.A": "Gross fixed capital formation",
  "P52.Q.USD.A": "Changes in inventories",
  "P52.Q.XDC.A": "Changes in inventories",
  "P52.V.USD.A": "Changes in inventories",
  "P52.V.XDC.A": "Changes in inventories",
  "P52_PS.Q.USD.A": "Changes in inventories, Private sector",
  "P52_PS.Q.XDC.A": "Changes in inventories, Private sector",
  "P52_PS.V.USD.A": "Changes in inventories, Private sector",
  "P52_PS.V.XDC.A": "Changes in inventories, Private sector",
  "P53.Q.USD.A": "Acquisitions less disposals of valuables",
  "P53.Q.XDC.A": "Acquisitions less disposals of valuables",
  "P53.V.USD.A": "Acquisitions less disposals of valuables",
  "P53.V.XDC.A": "Acquisitions less disposals of valuables",
  "P6.Q.USD.A": "Exports of goods and services",
  "P6.Q.XDC.A": "Exports of goods and services",
  "P6.V.USD.A": "Exports of goods and services",
  "P6.V.XDC.A": "Exports of goods and services",
  "P61.Q.USD.A": "Exports of goods",
  "P61.Q.XDC.A": "Exports of goods",
  "P61.V.USD.A": "Exports of goods",
  "P61.V.XDC.A": "Exports of goods",
  "P62.Q.USD.A": "Exports of services",
  "P62.Q.XDC.A": "Exports of services",
  "P62.V.USD.A": "Exports of services",
  "P62.V.XDC.A": "Exports of services",
  "P7.Q.USD.A": "Imports of goods and services",
  "P7.Q.XDC.A": "Imports of goods and services",
  "P7.V.USD.A": "Imports of goods and services",
  "P7.V.XDC.A": "Imports of goods and services",
  "P71.Q.USD.A": "Imports of goods",
  "P71.Q.XDC.A": "Imports of goods",
  "P71.V.USD.A": "Imports of goods",
  "P71.V.XDC.A": "Imports of goods",
  "P72.Q.USD.A": "Imports of services",
  "P72.Q.XDC.A": "Imports of services",
  "P72.V.USD.A": "Imports of services",
  "P72.V.XDC.A": "Imports of services",
  "YA0.Q.USD.A": "Statistical discrepancy (expenditure approach)",
  "YA0.Q.XDC.A": "Statistical discrepancy (expenditure approach)",
  "YA0.V.USD.A": "Statistical discrepancy (expenditure approach)",
  "YA0.V.XDC.A": "Statistical discrepancy (expenditure approach)"
};

// Reverse maps
export const IMF_WEO_DESC_TO_CODE: Record<string, string> = Object.fromEntries(
  Object.entries(IMF_WEO_CODE_TO_DESC).map(([c, d]) => [d, c])
);
export const IMF_NEA_DESC_TO_CODE: Record<string, string> = Object.fromEntries(
  Object.entries(IMF_NEA_CODE_TO_DESC).map(([c, d]) => [d, c])
);

// Pattern: IMF codes are typically uppercase alphanumerics with dots and a trailing period segment, e.g. NGDPD.A or B1GQ.V.XDC.A
const IMF_CODE_PATTERN = /^[A-Z0-9_]+(\.[A-Z0-9]+){1,4}$/;

export function getImfVariableCode(nameOrCode: string): string | undefined {
  // If caller already passed a valid IMF code
  if (IMF_CODE_PATTERN.test(nameOrCode) && (IMF_WEO_CODE_TO_DESC[nameOrCode] || IMF_NEA_CODE_TO_DESC[nameOrCode])) {
    return nameOrCode;
  }
  // Lookup by description (exact match) in WEO first, then NEA
  if (IMF_WEO_DESC_TO_CODE[nameOrCode]) return IMF_WEO_DESC_TO_CODE[nameOrCode];
  if (IMF_NEA_DESC_TO_CODE[nameOrCode]) return IMF_NEA_DESC_TO_CODE[nameOrCode];
  return undefined;
}
